#!/usr/bin/env python
"""
This script is a simple python node which imports
source code of std_messages_examples.
"""

import hello_world_package.module_one

if __name__ == '__main__':
    hello_world_package.module_one.main()